# Generated by Django 3.2.23 on 2024-01-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrashApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblWynoszenie',
        ),
    ]
