# Generated by Django 3.2.23 on 2024-01-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashApp', '0002_delete_tblwynoszenie'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblWynoszenie',
            fields=[
                ('id_empty', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('which_bin_field', models.IntegerField(db_column='which_bin_')),
                ('who_should', models.IntegerField()),
                ('who_did', models.IntegerField()),
                ('date', models.TextField()),
                ('add_points', models.IntegerField(blank=True, null=True)),
                ('sub_points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_wynoszenie',
            },
        ),
    ]
