# Generated by Django 3.2.23 on 2024-01-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashApp', '0003_tblwynoszenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblwynoszenie',
            name='which_bin_field',
            field=models.IntegerField(db_column='which_bin '),
        ),
    ]
