# Generated by Django 3.2.23 on 2024-01-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrashApp', '0004_alter_tblwynoszenie_which_bin_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblWynoszenie',
        ),
    ]
