# Generated by Django 3.2.23 on 2024-01-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashApp', '0005_delete_tblwynoszenie'),
    ]

    operations = [

    ]
