# Generated by Django 3.2.23 on 2024-01-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashApp', '0005_delete_tblwynoszenie'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblWynoszenie',
            fields=[
                ('id_empty', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('which_bin_field', models.IntegerField(db_column='which_bin ')),
                ('who_should', models.IntegerField()),
                ('who_did', models.IntegerField()),
                ('date', models.TextField()),
                ('add_points', models.IntegerField(blank=True, null=True)),
                ('sub_points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_wynoszenie',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tblbinlogs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblharmonogramwyn',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblkoszekonfiguracyjna',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbluzytkownicykonfig',
            options={'managed': False},
        ),
    ]
