# Generated by Django 3.2.23 on 2024-01-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashApp', '0007_auto_20240112_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblWynoszenie',
            fields=[
                ('id_empty', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('which_bin_field', models.IntegerField(db_column='which_bin ')),
                ('who_should', models.IntegerField()),
                ('who_did', models.IntegerField()),
                ('date', models.TextField()),
                ('add_points', models.IntegerField(blank=True, null=True)),
                ('sub_points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_wynoszenie',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
