# Generated by Django 3.2.23 on 2024-01-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrashApp', '0009_djangomigrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
    ]
