# Generated by Django 3.2.23 on 2024-01-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashApp', '0010_delete_djangomigrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblBinLogs',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date_log', models.TextField()),
                ('bin_id', models.IntegerField()),
                ('bin_status', models.TextField()),
            ],
            options={
                'db_table': 'tbl_bin_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblHarmonogramWyn',
            fields=[
                ('id_daty', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data', models.TextField()),
                ('bin_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_harmonogram_wyn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblKoszeKonfiguracyjna',
            fields=[
                ('id_bin', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bin_name', models.TextField(unique=True)),
                ('bin_depth', models.TextField()),
                ('emp_calendar', models.IntegerField()),
                ('emp_reminder', models.IntegerField()),
                ('adding_points', models.IntegerField()),
                ('subtrack_points', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_kosze_konfiguracyjna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUzytkownicyKonfig',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_name', models.TextField(unique=True)),
                ('user_mail', models.TextField()),
                ('statistics_days', models.IntegerField()),
                ('which_bin', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_uzytkownicy_konfig',
                'managed': False,
            },
        ),
    ]
